language: php

addons:
  apt:
    packages:
    - php-pear
    - libyaml-dev

php:
  - "7.0"

before_script:
  - composer self-update
  - composer install --no-scripts --no-interaction
  - composer dump-autoload -o
  - pecl install yaml-2.0.0

after_script:
    - php vendor/bin/coveralls -v

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
